COMMON: &common
  TABLEDAP: http://data-test.ooi.rutgers.edu/erddap/tabledap/
  ERDDAP_URL: http://data-test.ooi.rutgers.edu/erddap
  SERVICES_URL: http://localhost:4000
  DEBUG: False
  CACHE_TYPE: simple
  UI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  GOOGLE_ANALYTICS_URL: 'http://www.google-analytics.com/collect?v=1&tid=UA-50606390-3&cid=5555&t=pageview'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True


